version: "3.9"

services:
    server:
        container_name: server
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "3000:3000"
